// Public fields returned by GET /api/orders/:id.
// Keep this allow-list explicit: payment credentials, legacy OTPs and escrow
// bookkeeping must never be exposed by the customer/driver detail endpoint.
export const ORDER_DETAIL_PUBLIC_COLUMNS = [
  'id',
  'order_display_id',
  'customer_id',
  'driver_id',
  'truck_id',
  'status',
  'pickup_address',
  'pickup_lat',
  'pickup_lng',
  'drop_address',
  'drop_lat',
  'drop_lng',
  'pickup_date',
  'pickup_time',
  'goods_type',
  'weight_tonnes',
  'length_ft',
  'width_ft',
  'height_ft',
  'is_stackable',
  'is_fragile',
  'special_requirements',
  'total_amount',
  'cancellation_fee',
  'cancellation_reason',
  'driver_name',
  'driver_rating',
  'truck_number',
  'eta',
  'created_at',
  'updated_at',
].join(', ');
